### PR TITLE
Add PAA (on develop branch)

### PR DESCRIPTION
**Pull request by gbstack**
**PR types**

New features

**PR changes**

APIs

**Describe**

Hi,

This PR add PAA (Probalistic Anchor Assignment) implementation. Configuration files are located at _configs/paa_ directory.

Now the training is not done, I will submit the result after it's done.

(Original PR on release/2.3 branch: https://github.com/PaddlePaddle/PaddleDetection/pull/4568)

### CODE REVIEW

**Comment by lyuwenyu** [comment]
> **PR types**
> 
> New features
> 
> **PR changes**
> 
> APIs
> 
> **Describe**
> 
> Hi,
> 
> This PR add PAA (Probalistic Anchor Assignment) implementation. Configuration files are located at _configs/paa_ directory.
> 
> Now the training is not done, I will submit the result after it's done.
> 
> (Original PR on release/2.3 branch: #4568)

指标也贴一下吧

**Comment by gbstack** [comment]
> > **PR types**
> > New features
> > **PR changes**
> > APIs
> > **Describe**
> > Hi,
> > This PR add PAA (Probalistic Anchor Assignment) implementation. Configuration files are located at _configs/paa_ directory.
> > Now the training is not done, I will submit the result after it's done.
> > (Original PR on release/2.3 branch: #4568)
> 
> 指标也贴一下吧

指标是指训练评估结果吗？

**Comment by lyuwenyu** [comment]
是的 训练的结果

**Comment by gbstack** [comment]
> 是的 训练的结果

现在还没训练好，我训练好之后发上来吧

**Comment by lyuwenyu** [comment]
好的

**Pull request closed without merging**
