### PR TITLE
Fix some typos.

### PR DESCRIPTION
**Pull request by Yulv-git**
Fix some typos in *.md and code.

### CODE REVIEW

**Review by nemonameless — APPROVED** [review]

**Review by wangxinxin08 — APPROVED** [review]
LGTM

**Review by nemonameless — COMMENTED** [review]
Please also cherry-pick to develop branch. Thanks very much.

**Comment by Yulv-git** [comment]
> Please also cherry-pick to develop branch. Thanks very much.

I am not familiar with the `git cherry-pick` operation at present. Do I need to make related changes in the develop branch?

**Comment by nemonameless** [comment]
> > Please also cherry-pick to develop branch. Thanks very much.
> 
> I am not familiar with the `git cherry-pick` operation at present. Do I need to make related changes in the develop branch?

```
git checkout develop
git cherry-pick c28e27e
git cherry-pick 3ef0ea8
git push -u origin develop
```
and maybe you should fix some conflicts. Thanks.

**Comment by Yulv-git** [comment]
> > > Please also cherry-pick to develop branch. Thanks very much.
> > 
> > 
> > I am not familiar with the `git cherry-pick` operation at present. Do I need to make related changes in the develop branch?
> 
> ```
> git checkout develop
> git cherry-pick c28e27e
> git cherry-pick 3ef0ea8
> git push -u origin develop
> ```
> 
> and maybe you should fix some conflicts. Thanks.

Thanks for your help!
I just created a PR to implement the cherry-pick operation described above. See https://github.com/PaddlePaddle/PaddleDetection/pull/5873 for details.

**Pull request merged**
