### PR TITLE
Change installation order of PaddleDetection

### PR DESCRIPTION
**Pull request by hz1943**
Using original order will cause weird exception, like "RuntimeError: implement_array_function method already has a docstring", "AssertionError: PyTypeTest on non extension type"...
Enviroment: AI Studio(2.1.2)

### CODE REVIEW

**Comment by lyuwenyu** [comment]
Hi  @hz1943,   可以提个到develop分支的PR嘛

**Comment by hz1943** [comment]
> Hi @hz1943, 可以提个到develop分支的PR嘛

Hi @lyuwenyu 我已经提了到develop分支的PR

**Comment by lyuwenyu** [comment]
Hi @hz1943,  没看到你的新PR啊  你需要按照下图提一个新的PR 选择develop  （ 然后你把新PR的链接放这里
image

**Comment by hz1943** [comment]
Hi, @lyuwenyu 不好意思。新的PR链接在这里，https://github.com/PaddlePaddle/PaddleDetection/pull/4194

**Pull request closed without merging**
