### PR TITLE
Clean code

### PR DESCRIPTION
**Pull request by qingqing01**
1. rm ppdet/ext_op
2. rm ppdet/data/tests
3. rm ppdet/utils/oid_eval.py , ...

### CODE REVIEW

**Review by heavengate — DISMISSED** [review]

**Review by jerrywgz — COMMENTED** [review]
ppdet/utils/data_structure.py & ppdet/py_op/post_processing.py could be removed

**Comment by qingqing01** [comment]
@jerrywgz Done.

**Review by wangxinxin08 — COMMENTED** [review]
ppdet/modeling/tests/test_transform.py and ppdet/modeling/tests/test_yolo_loss.py can be also removed

**Review by jerrywgz — APPROVED** [review]
LGTM

**Pull request merged**
