### PR TITLE
Fix "onnx-graphsurgeon" into "onnx_graphsurgeon" word typo in  #8829 

### PR DESCRIPTION
**Pull request by jzhang533**

### CODE REVIEW

**Review by Aurelius84 — APPROVED** [review]

**Comment by jzhang533** [comment]
it seems CI of this project is out of maintenance. (not only this PR, but also the recent incoming PRs are suffering from CI's broken).

Can anyone help? @lyuwenyu @michaelowenliu @tianshuo78520a

**Comment by jzhang533** [comment]
@yinger78 @cfdx-gh

please fix CI.

**Review by lyuwenyu — APPROVED** [review]
lgtm

**Comment by jzhang533** [comment]
will merge. and considering deprecate PaddleDetection-ci, will try to use github action to setup a replacement.

**Pull request merged**
